name: preload_google_ads  # The name of your plugin as it'll appear on pub.dev
description: "Preloading Google Ads in Flutter loads ads in the background for quick display."
version: 1.0.0  # Semantic versioning â€” update this with each release
homepage: https://github.com/bhx20/Preload-Google-Ads  # Link to your plugin's GitHub repo or docs

environment:
  sdk: ">=3.6.0 <4.0.0"       # Specifies Dart SDK compatibility
  flutter: ">=3.3.0"          # Minimum Flutter SDK version required

dependencies:
  flutter:
    sdk: flutter              # Core Flutter dependency
  google_mobile_ads: ^6.0.0   # Google Mobile Ads SDK for Flutter (official package)

dev_dependencies:
  flutter_test:
    sdk: flutter              # Used for writing tests
  flutter_lints: ^5.0.0       # Enforces recommended linting rules for clean code

flutter:
  plugin:
    implements: preload_google_ads    # declare implements
    platforms:
      android:                
        package: com.plug.preload             # Android package name for plugin registration
        pluginClass: PreloadGoogleAdsPlugin   # The class that implements the Android plugin logic
      ios:               
        package: com.plug.preload             # iOS package name for plugin registration
        pluginClass: PreloadGoogleAdsPlugin   # The class that implements the iOS plugin logic
